os:
  - linux
  - osx
language: python
sudo: true
env:
  - TEST_MODE=run_tests
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-sklearn python-numpy python-scipy
  - virtualenv --system-site-packages .venv && source .venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
script: test/run.sh
notifications:
  email:
    on_success: never
