os:
  - linux
language: python
sudo: false
env:
  - TEST_MODE=run_tests
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
addons:
  apt:
    packages:
    - python-sklearn
    - python-numpy
    - python-scipy
    - python-matplotlib
    - ipython
    - ipython-notebook
    - python-pandas
    - python-sympy
    - libpq-dev
    - python-dev
install:
  - virtualenv --system-site-packages .venv && source .venv/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
script: test/run.sh
notifications:
  email:
    on_success: never
